import type { BusinessCategory } from '@/types/api';

interface CategoryColor {
  bg: string;
  text: string;
  border: string;
  cardAccent: string;     // border-t color for card top accent stripe
  selectedBg: string;
  selectedText: string;
}

export const CATEGORY_COLORS: Record<BusinessCategory, CategoryColor> = {
  // Beauty — pinks / roses
  barbershop_men: {
    bg: 'bg-slate-200',
    text: 'text-slate-800',
    border: 'border-slate-300',
    cardAccent: 'border-t-slate-500',
    selectedBg: 'bg-slate-700',
    selectedText: 'text-white',
  },
  hair_salon_women: {
    bg: 'bg-pink-100',
    text: 'text-pink-800',
    border: 'border-pink-300',
    cardAccent: 'border-t-pink-500',
    selectedBg: 'bg-pink-600',
    selectedText: 'text-white',
  },
  nail_salon: {
    bg: 'bg-rose-100',
    text: 'text-rose-800',
    border: 'border-rose-300',
    cardAccent: 'border-t-rose-500',
    selectedBg: 'bg-rose-600',
    selectedText: 'text-white',
  },
  eyebrows: {
    bg: 'bg-fuchsia-100',
    text: 'text-fuchsia-800',
    border: 'border-fuchsia-300',
    cardAccent: 'border-t-fuchsia-500',
    selectedBg: 'bg-fuchsia-600',
    selectedText: 'text-white',
  },
  makeup: {
    bg: 'bg-pink-200',
    text: 'text-pink-900',
    border: 'border-pink-400',
    cardAccent: 'border-t-pink-600',
    selectedBg: 'bg-pink-700',
    selectedText: 'text-white',
  },
  cosmetician: {
    bg: 'bg-rose-200',
    text: 'text-rose-900',
    border: 'border-rose-400',
    cardAccent: 'border-t-rose-600',
    selectedBg: 'bg-rose-700',
    selectedText: 'text-white',
  },
  spa: {
    bg: 'bg-purple-100',
    text: 'text-purple-800',
    border: 'border-purple-300',
    cardAccent: 'border-t-purple-500',
    selectedBg: 'bg-purple-600',
    selectedText: 'text-white',
  },
  massage: {
    bg: 'bg-violet-100',
    text: 'text-violet-800',
    border: 'border-violet-300',
    cardAccent: 'border-t-violet-500',
    selectedBg: 'bg-violet-600',
    selectedText: 'text-white',
  },
  tattoo: {
    bg: 'bg-zinc-200',
    text: 'text-zinc-900',
    border: 'border-zinc-400',
    cardAccent: 'border-t-zinc-600',
    selectedBg: 'bg-zinc-700',
    selectedText: 'text-white',
  },
  piercing: {
    bg: 'bg-stone-200',
    text: 'text-stone-800',
    border: 'border-stone-300',
    cardAccent: 'border-t-stone-500',
    selectedBg: 'bg-stone-600',
    selectedText: 'text-white',
  },
  laser_hair_removal: {
    bg: 'bg-pink-50',
    text: 'text-pink-700',
    border: 'border-pink-200',
    cardAccent: 'border-t-pink-400',
    selectedBg: 'bg-pink-500',
    selectedText: 'text-white',
  },
  // Health — blues / cyans
  doctor: {
    bg: 'bg-sky-100',
    text: 'text-sky-800',
    border: 'border-sky-300',
    cardAccent: 'border-t-sky-500',
    selectedBg: 'bg-sky-600',
    selectedText: 'text-white',
  },
  dentist: {
    bg: 'bg-cyan-100',
    text: 'text-cyan-800',
    border: 'border-cyan-300',
    cardAccent: 'border-t-cyan-500',
    selectedBg: 'bg-cyan-600',
    selectedText: 'text-white',
  },
  physiotherapy: {
    bg: 'bg-blue-100',
    text: 'text-blue-800',
    border: 'border-blue-300',
    cardAccent: 'border-t-blue-500',
    selectedBg: 'bg-blue-600',
    selectedText: 'text-white',
  },
  psychologist: {
    bg: 'bg-indigo-100',
    text: 'text-indigo-800',
    border: 'border-indigo-300',
    cardAccent: 'border-t-indigo-500',
    selectedBg: 'bg-indigo-600',
    selectedText: 'text-white',
  },
  nutritionist: {
    bg: 'bg-teal-100',
    text: 'text-teal-800',
    border: 'border-teal-300',
    cardAccent: 'border-t-teal-500',
    selectedBg: 'bg-teal-600',
    selectedText: 'text-white',
  },
  alternative_medicine: {
    bg: 'bg-sky-50',
    text: 'text-sky-700',
    border: 'border-sky-200',
    cardAccent: 'border-t-sky-400',
    selectedBg: 'bg-sky-500',
    selectedText: 'text-white',
  },
  // Animals
  veterinary: {
    bg: 'bg-amber-100',
    text: 'text-amber-800',
    border: 'border-amber-300',
    cardAccent: 'border-t-amber-500',
    selectedBg: 'bg-amber-600',
    selectedText: 'text-white',
  },
  pet_grooming: {
    bg: 'bg-orange-100',
    text: 'text-orange-800',
    border: 'border-orange-300',
    cardAccent: 'border-t-orange-500',
    selectedBg: 'bg-orange-600',
    selectedText: 'text-white',
  },
  // Fitness — emeralds / greens
  yoga: {
    bg: 'bg-emerald-100',
    text: 'text-emerald-800',
    border: 'border-emerald-300',
    cardAccent: 'border-t-emerald-500',
    selectedBg: 'bg-emerald-600',
    selectedText: 'text-white',
  },
  pilates: {
    bg: 'bg-green-100',
    text: 'text-green-800',
    border: 'border-green-300',
    cardAccent: 'border-t-green-500',
    selectedBg: 'bg-green-600',
    selectedText: 'text-white',
  },
  personal_training: {
    bg: 'bg-lime-100',
    text: 'text-lime-800',
    border: 'border-lime-300',
    cardAccent: 'border-t-lime-500',
    selectedBg: 'bg-lime-600',
    selectedText: 'text-white',
  },
  // Creative / Education
  dance_studio: {
    bg: 'bg-fuchsia-50',
    text: 'text-fuchsia-700',
    border: 'border-fuchsia-200',
    cardAccent: 'border-t-fuchsia-400',
    selectedBg: 'bg-fuchsia-500',
    selectedText: 'text-white',
  },
  music_lessons: {
    bg: 'bg-yellow-100',
    text: 'text-yellow-800',
    border: 'border-yellow-300',
    cardAccent: 'border-t-yellow-500',
    selectedBg: 'bg-yellow-600',
    selectedText: 'text-white',
  },
  tutoring: {
    bg: 'bg-blue-50',
    text: 'text-blue-700',
    border: 'border-blue-200',
    cardAccent: 'border-t-blue-400',
    selectedBg: 'bg-blue-500',
    selectedText: 'text-white',
  },
  driving_school: {
    bg: 'bg-violet-50',
    text: 'text-violet-700',
    border: 'border-violet-200',
    cardAccent: 'border-t-violet-400',
    selectedBg: 'bg-violet-500',
    selectedText: 'text-white',
  },
  photography: {
    bg: 'bg-amber-50',
    text: 'text-amber-700',
    border: 'border-amber-200',
    cardAccent: 'border-t-amber-400',
    selectedBg: 'bg-amber-500',
    selectedText: 'text-white',
  },
  event_planning: {
    bg: 'bg-purple-50',
    text: 'text-purple-700',
    border: 'border-purple-200',
    cardAccent: 'border-t-purple-400',
    selectedBg: 'bg-purple-500',
    selectedText: 'text-white',
  },
  // Automotive — slates / grays
  car_wash: {
    bg: 'bg-slate-100',
    text: 'text-slate-700',
    border: 'border-slate-300',
    cardAccent: 'border-t-slate-400',
    selectedBg: 'bg-slate-500',
    selectedText: 'text-white',
  },
  car_repair: {
    bg: 'bg-gray-200',
    text: 'text-gray-800',
    border: 'border-gray-400',
    cardAccent: 'border-t-gray-600',
    selectedBg: 'bg-gray-700',
    selectedText: 'text-white',
  },
  cleaning_service: {
    bg: 'bg-cyan-50',
    text: 'text-cyan-700',
    border: 'border-cyan-200',
    cardAccent: 'border-t-cyan-400',
    selectedBg: 'bg-cyan-500',
    selectedText: 'text-white',
  },
  other: {
    bg: 'bg-zinc-200',
    text: 'text-zinc-800',
    border: 'border-zinc-300',
    cardAccent: 'border-t-zinc-500',
    selectedBg: 'bg-zinc-600',
    selectedText: 'text-white',
  },
};
